### ISSUE TITLE
index out of range when discovering estimote

### ISSUE THREAD

**Issue by aperritano** [sandeepmistry/node-bleacon#30]
Hi I did a small test to see how this project works. I tried running the following code: 
var Estimote = require('bleacon').Estimote;
Estimote.discover(function(estimote){
    console.log('working', estimote);
});

each time I run it with my estimote i get the following. Any ideas how to work around this?  

buffer.js:506
    throw new RangeError('index out of range');
          ^
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt16LE (buffer.js:552:5)
    at new Estimote (/Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/estimote/estimote.js:47:28)
    at Noble.Util.inherits.constructor.onDiscover (/Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/node_modules/noble-device/lib/util.js:28:22)
    at Noble.emit (events.js:129:20)
    at Noble.onDiscover (/Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/node_modules/noble/lib/noble.js:141:10)
    at emit (events.js:118:17)
    at null.<anonymous> (/Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/node_modules/noble/lib/mac/yosemite.js:174:12)
    at /Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/node_modules/noble/lib/mac/uuid-to-address.js:22:5
    at tryParseBuffer (/Users/aperritano/Box Sync/dev/uic-phd/NodeBeacon/node_modules/bleacon/node_modules/noble/node_modules/bplist-p

**Comment by sandeepmistry** [comment]
@aperritano strange, what firmware version are you running on the beacons?

Could you please provide debug output: ```DEBUG=* node <file>.js```

**Comment by sandeepmistry** [comment]
@aperritano any updates?

**Comment by sandeepmistry** [comment]
Closing due to lack of activity, please re-open with requested info ...
