### ISSUE TITLE
Node issue with MAC OS X El Capitain

### ISSUE THREAD

**Issue by parvezq** [sandeepmistry/node-bleacon#42]
Note: This works perfectly well in Yosemite MAC OS X
Problem: I have used test.js to make mac os x advertise an IBeacon which is detectable by an iOS application. When I try to use it on MAC OS X El Capitain via below command
node /Users/parvezqureshi/Downloads/node-bleacon-master/test.js
 then it is giving errors:

`throw error;
      ^

Error: Could not start advertising, state is unsupported (not poweredOn)
    at Bleno.startAdvertisingIBeacon (/Users/parvezqureshi/node_modules/bleno/lib/bleno.js:121:17)
    at Bleno.<anonymous> (/Users/parvezqureshi/Downloads/node-bleacon-master/lib/bleacon.js:33:13)
    at emitOne (events.js:77:13)
    at Bleno.emit (events.js:169:7)
    at Bleno.onStateChange (/Users/parvezqureshi/node_modules/bleno/lib/bleno.js:66:8)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/parvezqureshi/node_modules/bleno/lib/mac/bindings.js:98:8)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)`

I have checked that Bluetooth is already on on the Mac OS X machine
What has changed from Yosemite to El Capitain that is causing this issue ? Version of El Capitain is 10.11.1
@sandeepmistry Can you please tell what can be the cause of this issue?

The contents of test.js are as below:

`var Bleacon = require('./index');

Bleacon.startAdvertising('e2c56db5dffb48d2b060d0f5a71096e0', 0, 0, -59);

Bleacon.on('discover', function(bleacon) {
  console.log('bleacon found: ' + JSON.stringify(bleacon));
});

Bleacon.startScanning(/*'e2c56db5dffb48d2b060d0f5a71096e0', 0, 0*/);

`

**Comment by sandeepmistry** [comment]
@parvezq things look ok on my OS X 10.11.3 Mac.

Could you please provide debug logs? ```DEBUG=* node test.js```

**Comment by sandeepmistry** [comment]
I'm closing this for now due to lack of discussion.
